services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - zlahoda-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - zlahoda-network
    depends_on:
      - backend

networks:
  zlahoda-network:
    driver: bridge